### ISSUE TITLE
Tell the users about ``koch temp``

### ISSUE THREAD

**Issue by Araq** [juancarlospaco/nim-new-backend#1]
Instead of

```
$ ./koch boot
$ bin/nim js -d:release -d:danger example.nim
```

developers are better served with

```
$ ./koch temp js -d:release -d:danger example.nim
```

**Comment by juancarlospaco** [comment]
Thanks for the idea, yeah I started this like *thinking out loud* but in code. 
It "compiles" to Python (???) but some stuff is still JavaScript. :rofl:
